### ISSUE TITLE
Cannot download processed data

### ISSUE THREAD

**Issue by ye0223** [timoast/MPAL-hg38#1]
Hi,

I ran the code `aws s3 sync s3://mpal-hg38/public/ . --request-payer` to download the processed data but it failed with this error message.
`fatal error: Unable to locate credentials`

Can you update the credentials please?

Thank you.

**Comment by timoast** [comment]
These are _your_ credentials for AWS

See https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-configure.html
